-- MySQL Script generated by MySQL Workbench
-- Sun Jul 17 11:27:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
-- SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb_jsp_practice` DEFAULT CHARACTER SET utf8 ;
USE `mydb_jsp_practice` ;

-- drop database if exists mydb_jsp_practice;
-- -----------------------------------------------------
-- Table `mydb`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_jsp_practice`.`employees` (
  `documentType` VARCHAR(30) NOT NULL,
  `documentNumber` VARCHAR(45) NOT NULL,
  `name` VARCHAR(50) NULL,
  `lastName` VARCHAR(50) NULL,
  `age` INT NULL,
  `birthDate` DATE NULL,
  PRIMARY KEY (`documentType`, `documentNumber`)) ;


-- -----------------------------------------------------
-- Table `mydb`.`systemUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb_jsp_practice`.`systemUsers` (
  `email` VARCHAR(100) NOT NULL,
  `password` BLOB NOT NULL,
  PRIMARY KEY (`email`)) ;


-- SET SQL_MODE=@OLD_SQL_MODE;
-- SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
